name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:

  build:
    runs-on: [self-hosted, arm64]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
      with:
        egress-policy: audit

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: '>=1.23.0'
        cache: false

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
