name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:

  build:
    runs-on: [self-hosted, arm64]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Go
      uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: '>=1.23.0'
        cache: false

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
